spring:
  application:
    name: fulfillment
  threads:
    virtual:
      enabled: true

server:
  port: ${SERVER_PORT:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Consumidor de fulfillment do OrderLab
