otel.service.name=pricing
otel.traces.exporter=otlp
otel.exporter.otlp.endpoint=http://localhost:4318
otel.exporter.otlp.protocol=http/protobuf
otel.metrics.exporter=none
otel.logs.exporter=none
otel.instrumentation.http.server.capture-request-headers=x-load-test
otel.resource.attributes=service.version=0.1.0-SNAPSHOT,deployment.environment.name=local
